src/main/java/jp/co/us717/model/ResBean.java
package jp.co.us717.model;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;
import java.util.Objects;
import java.util.Random;

import jp.co.us717.exception.GeneralErrorException;
import jp.co.us717.exception.IORuntimeException;
import jp.co.us717.exception.SQLRuntimeException;
import jp.co.us717.lib.BeanCommonFunction;

import org.apache.commons.lang3.StringUtils;

/**
 * レス。<br>
 */
public class ResBean extends BeanCommonFunction {

    /** スレッドID */
    private int threadId_;

    /** レス番号 */
    private int resNum_;

    /** 投稿者の名前 */
    private String poster_;

    /** ファイル名 */
    private String filename_;

    /** 投稿日 */
    private String postDate_;

    /** パスワード */
    private String password_;

    /** パスワードの有無*/
    private boolean isPassword_;

    /** 画像データ */
    private String postImage_;

    /** 画像パス */
    private String imagePath_;

    /** 状態 */
    private boolean isShow_;

    /** IPアドレス */
    private String addres_;

    /**
     * コンストラクタ。
     */
    public ResBean() {
        poster_ = "名無し";
        filename_ = "";
        postDate_ = "";
        password_ = "0000";
        postImage_ = "";
        imagePath_ = "";
        addres_ = "";
    }

    /**
     * レスを投稿する。<br>
     * !スレッドID・投稿者・ファイル名・パスワード
     * @throws SQLRuntimeException レスの投稿に失敗した場合
     * @throws IORuntimeException  画像データの保存に失敗した場合
     */
    public void InsertRes() {

        //!ファイル名を作成する（現時刻+乱数)
        Date curDate = new Date();
        DateFormat reformDate = new SimpleDateFormat("yyMMddHHmmss");
        Random rand = new Random();
        filename_ = reformDate.format(curDate) + rand.nextInt(999) + ".jpg";

        //!画像データをデコードしてディレクトリに保存
        File file = new File(realPath_ + "/" + filename_);
        try (FileChannel fc = FileChannel.open(file.toPath(), StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
                FileLock lock = fc.tryLock()) {
            if (lock == null) {
                throw new GeneralErrorException();
            }
            byte[] encodedData = Base64.getDecoder().decode(postImage_);
            ByteBuffer buf = ByteBuffer.wrap(encodedData);
            fc.write(buf);
        } catch (IOException e) {
            throw new IORuntimeException(e);
        }

        //!SQL定義
        //====レスの新規作成========
        String sqlRes = "insert into res(thread_id, poster, filename, postdate, is_password, password, addres )"
                + "values(?, ?, ?, now(), ?, ?, ?)";
        //====スレッドの最終更新日更新,レス数 ======
        String sqlThread = "update thread set last_update = now(), res_count = res_count + 1 where thread_id = ? and state = true";

        //!DB更新
        try (Connection con = dataSource_.getConnection();
                PreparedStatement stmRes = con.prepareStatement(sqlRes);
                PreparedStatement stmThread = con.prepareStatement(sqlThread)) {
            try {
                //トランザクション開始
                con.setAutoCommit(false);

                //レス新規作成
                stmRes.setInt(1, threadId_);
                stmRes.setString(2, poster_);
                stmRes.setString(3, filename_);
                stmRes.setBoolean(4, isPassword_);
                stmRes.setString(5, password_);
                stmRes.setString(6, addres_);
                stmRes.executeUpdate();

                //threadの最終更新日、レス数を更新する
                stmThread.setInt(1, threadId_);
                if (stmThread.executeUpdate() != 1) { //スレッドが書き込み禁止だった場合中止
                    throw new SQLException("ERROR:スレッドが書き込み禁止状態です。スレッド" + threadId_);
                }

                //コミット
                con.commit();

            } catch (SQLException ex) {
                con.rollback();
                throw ex;
            } finally {
                con.setAutoCommit(true);
            }
        } catch (SQLException e) {
            //削除
            try {
                Files.deleteIfExists(file.toPath());//失敗したので、既に保存していた画像を削除する
            } catch (IOException ex) {
                throw new IORuntimeException(ex);
            }
            throw new SQLRuntimeException(e);
        }
    }

    /**
     * レスを表示禁止にする。<br>
     * !スレッドID・レス番号・パスワード
     * @throws SQLRuntimeException レスの書き込み禁止に失敗した場合
     */
    public void ProhibitionOfResShowing() {
        String sqlUpdate = "update res set state = false where filename in(select filename from res "
                + " where thread_id = ? order by postdate asc offset ? limit 1 ) and is_password = true and"
                + " password = ?";
        try (Connection con = dataSource_.getConnection();
                PreparedStatement stmGetDeleteFileName = con.prepareStatement(sqlUpdate)) {

            //データ取得
            stmGetDeleteFileName.setInt(1, threadId_);
            stmGetDeleteFileName.setInt(2, resNum_ - 1);
            stmGetDeleteFileName.setString(3, password_);
            if (stmGetDeleteFileName.executeUpdate() != 1) {
                throw new SQLException("書き込み禁止に失敗しました");
            }
        } catch (SQLException e) {
            throw new SQLRuntimeException(e);
        }
    }

    /**
     * レス番号の設定。
     * @param resNum レス番号
     */
    public void setResNum(int resNum) {
        resNum_ = resNum;
    }

    /**
     * スレッドIDの設定。
     * @param threadId 投稿するDB内のスレッドID
     */
    public void setThreadId(int threadId) {
        if (threadId <= 0) {
            throw new IllegalArgumentException("0以上を指定してください");
        }
        threadId_ = threadId;
    }

    /**
     * 投稿者の名前設定。<br>
     * 任意。<br>
     * 空文字、NULL、スペースを設定した場合はデフォルトの名前で設定は反映されません。
     * @param poster 投稿者の名前
     */
    public void setPoster(String poster) {
        if (!StringUtils.isBlank(poster)) {
            poster_ = poster.trim();
        } else {
            poster_ = "名無し"; //デフォルトの投稿者名
        }
    }

    /**
     * 投稿日の設定。
     * @param postDate 投稿日
     */
    public void setPostDate(String postDate) {
        postDate_ = Objects.requireNonNull(postDate);
    }

    /**
     * パスワードの設定。<br>
     * 任意<br>
     * 半角英数字を設定して下さい。<br>
     * 半角英数字以外の場合、パスワードは設定されません。
     * @param password 削除用のパスワード(半角英数字)
     */
    public void setPassword(String password) {
        if (!StringUtils.isBlank(password) && password.matches("^[a-zA-Z0-9]+$")) {
            password_ = password.trim();
            isPassword_ = true;
        } else {
            password_ = "0000";
            isPassword_ = false;
        }
    }

    /**
     * パスワードの有無の設定。
     * @param isPassword パスワードの有無
     */
    public void setIsPassword(boolean isPassword) {
        isPassword_ = isPassword;
    }

    /**
     * 画像データの設定。
     * @param postImage デコードして保存する画像データ
     */
    public void setImageData(String postImage) {
        postImage_ = Objects.requireNonNull(postImage);
    }

    /**
     * 画像パスの設定。
     * @param imagePath 画像パス
     */
    public void setImagePath(String imagePath) {
        imagePath_ = Objects.requireNonNull(imagePath);
    }

    /**
     * 状態の設定。
     * @param isShow 状態
     */
    public void setIsShow(boolean isShow) {
        isShow_ = isShow;
    }

    /**
     * IPアドレスの設定。
     * @param addres IPアドレス
     */
    public void setAddres(String addres) {
        addres_ = Objects.requireNonNull(addres);
    }

    /**
     * レス番号の取得。
     * @return レス番号
     */
    public int getResNum() {
        return resNum_;
    }

    /**
     * スレッドIDの取得。
     * @return スレッドID
     */
    public int getThreadId() {
        return threadId_;
    }

    /**
     * 投稿者の名前取得。
     * @return 投稿者のい名前
     */
    public String getPoster() {
        return poster_;
    }

    /**
     * 投稿日取得の取得。
     * @return 投稿日
     */
    public String getPostDate() {
        return postDate_;
    }

    /**
     * パスワードの取得。
     * @return パスワード
     */
    public String getPassword() {
        return password_;
    }

    /**
     * パスワードの有無取得。
     * @return パスワードの有無
     */
    public boolean isPassword() {
        return isPassword_;
    }

    /**
     * 画像パスの取得。
     * @return 画像パス
     */
    public String getImagePath() {
        return imagePath_;
    }

    /**
     * 状態の取得。
     * @return 状態
     */
    public boolean isShow() {
        return isShow_;
    }
}

src/main/webapp/WEB-INF/jsp/error.jsp
<%@ page contentType="text/html; charset=UTF-8" errorPage="/jsp/error.jsp"%>
<%@ page trimDirectiveWhitespaces="true"%>
<!DOCTYPE html>

<html>
<head>
<meta charset="UTF-8" />
<link rel="shortcut icon" href="<%=request.getContextPath()%>/favicon.ico">
<style>
    body{text-align:center;}
</style>
<title>お絵かき掲示板SHIGEMI</title>
</head>
<body>
  <h1>ページエラー</h1>
  <img id="errorImage" src="<%=request.getContextPath()%>/Draw/deleteB.png">
</body>
</html>

src/main/webapp/WEB-INF/jsp/headlineF.jsp
<%@ page contentType="text/html; charset=UTF-8" errorPage="/WEB-INF/jsp/error.jsp"%>
<%@ page trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link rel="shortcut icon" href="<%=request.getContextPath()%>/favicon.ico">
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/headline.css" type="text/css"/>
<script src="<%=request.getContextPath()%>/js/delete.js"></script>
<title>お絵かき掲示板SHIGEMI</title>
</head>

<body>
    <div id="title">
    <h1>お絵かき掲示板(β)</h1>
    <h1>SHIGEMI</h1>
    <img src="<%=request.getContextPath()%>/Draw/shigemi.jpg" width="150px">
    </div>

    <table id="info">
    <tr>
        <td><a href="<%=request.getContextPath()%>/jsp/headline.jsp">トップ</a></td>
        <td><a href="<%=request.getContextPath()%>/jsp/faq.jsp">使い方</a></td>
        <td><a href="<%=request.getContextPath()%>/jsp/info.jsp">お知らせ</a></td>
        <td><a href="<%=request.getContextPath()%>/jsp/createthread.jsp">スレッド作成</a></td>
    </tr>
    </table>

    <div id="threadList">
        <table>
        <c:forEach var="table" items="${threadTable}" varStatus="status"  >
            <tr>
                <td>
                <c:out value="${status.count}." />
                </td>
                <td>
                <a href="<%=request.getContextPath()%><c:out value="/jsp/thread.jsp?thread=${table.threadId}" />">
                <c:out value="${table.threadName}"/>&nbsp;<c:out value="(${table.resCount})" />
                </a>
                </td>
            <tr>
        </c:forEach>
        </table>
    </div><hr>

    <%-- スレッド表示 --%>
    <c:forEach var="thread" items="${headlineThread}">
        <div id="res">
        <h3><c:out value="${thread.threadName}" /> </h3>

        <%-- 各スレッドの新着レス表示 --%>
        <c:if test="${thread.resCount>0}">
        <div>
            <c:forEach var="res" items="${headlineRes[thread.threadId]}">
                <c:if test="${res.show}">
                <dl>
                <dt>
                    ${res.resNum}:
                    <c:out value="${res.poster}"/>:
                    <fmt:parseDate var="result" value="${res.postDate}" pattern="yyyy-MM-dd HH:mm:ss" />
                    <span><fmt:formatDate value="${result}" pattern="yyyy/MM/dd(E) HH:mm:ss" /></span>
                    <a href="<%=request.getContextPath()%>/jsp/delete_nonejs.jsp?thread=${thread.threadId}"
                     onClick="openWnd('<%=request.getContextPath()%>/jsp/delete.jsp?thread=${thread.threadId}&num=${res.resNum}'); return false;">削除</a>
                    <a target="_blank"
                    href="<%=request.getContextPath()%><c:out value="/Draw/${res.imagePath}" />">
                     別ページ
                    </a>
                </dt>
                <dd>
                    <div id="resImage">
                    <img class="resImage" src="<%=request.getContextPath()%><c:out value="/Draw/${res.imagePath}" />">
                    </div>
                </dd>
                </dl>
                </c:if>
                <c:if test="${!res.show}">
                <dl>
                <dt>
                    ${res.resNum}:
                    <c:out value="${res.poster}"/>
                    <fmt:parseDate var="result" value="${res.postDate}" pattern="yyyy-MM-dd HH:mm:ss" />
                    <span><fmt:formatDate value="${result}" pattern="yyyy/MM/dd(E) HH:mm:ss" /></span>
                </dt>
                <dd>
                    <img src="<%=request.getContextPath()%><c:out value="/Draw/delete.jpg" />">
                </dd>
                </dl>
                </c:if>
            </c:forEach>
        </div>
        </c:if>

        <div id="threadLink">
            <a href="<%=request.getContextPath()%><c:out value="/jsp/thread.jsp?thread=${thread.threadId}" />">全て表示</a>
        </div>
        </div>
    </c:forEach><hr>

    <%-- ページ移動 --%>
    <div id="pageMove">
        <form method="get" action="<%=request.getContextPath()%>/jsp/headline.jsp">
        <table>
            <tr>
            <%-- スレッドがあるかチェック --%>
            <c:if var="isThread" test="${threadTable.size()>0}" />
            <c:if test="${isThread}">

                <%-- 前のページ --%>
                <c:if var="isPrePage" test="${page!=0}" />
                <c:if test="${isPrePage}">
                    <th><button type="submit" name="page" value="<c:out value="${page-1}"/>">前のページ</button></th>
                </c:if>
                <c:if test="${!isPrePage}">
                    <th>前のページ</th>
                </c:if>

                <%-- ページ移動 --%>
                <c:set var="threadSize" value="${threadTable.size()-1}" />
                <c:set var="totalPage" value="${threadSize/articleNum}" />
                <c:forEach begin="0" end="${totalPage}" varStatus="status">
                    <c:if test="${page==status.index}" var="isCurrentPage" />
                    <c:if test="${!isCurrentPage}">
                        <th>
                            <a class="nonVisit" href="<%=request.getContextPath()%>/jsp/headline.jsp?page=${status.index}">
                            <c:out value="[${status.index}]" /></a>
                        </th>
                    </c:if>
                    <c:if test="${isCurrentPage}">
                        <th><c:out value="[${status.index}]" /></th>
                    </c:if>
                </c:forEach>

                <%-- 次のページ --%>
                <c:if var="isNextPage" test="${(page+1)*articleNum<threadTable.size()}" />
                <c:if test="${isNextPage}">
                    <th><button type="submit" name="page" value="<c:out value="${page+1}"/>">次のページ</button></th>
                </c:if>
                <c:if test="${!isNextPage}">
                    <th>次のページ</th>
                </c:if>
            </c:if>

            <c:if test="${!isThread}">
                <th>[0]</th>
            </c:if>
           </tr>
        </table>
        </form>
    </div>
</body>

<footer>
    <p>Copyright© 2015 PaintShigemi All Rights Reserved</p>
</footer>

</html>

src/main/webapp/WEB-INF/jsp/threadF.jsp
<%@ page contentType="text/html; charset=UTF-8" errorPage="/WEB-INF/jsp/error.jsp"%>
<%@ page trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<link rel="shortcut icon" href="<%=request.getContextPath()%>/favicon.ico">
<link rel="stylesheet" href="<%=request.getContextPath()%>/lib/jquery.simple-color-picker.css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/lib/ui/jquery-ui.min.css" />
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/headline.css" type="text/css"/>
<link rel="stylesheet" href="<%=request.getContextPath()%>/css/thread.css" type="text/css"/>
<script src="<%=request.getContextPath()%>/lib/jquery-2.1.1.min.js"></script>
<script src="<%=request.getContextPath()%>/lib/jquery.validate.min.js"></script>
<script src="<%=request.getContextPath()%>/lib/validate-custom.js"></script>
<script src="<%=request.getContextPath()%>/lib/messages_ja.min.js"></script>
<script src="<%=request.getContextPath()%>/lib/jquery.simple-color-picker.js"></script>
<script src="<%=request.getContextPath()%>/lib/ui/jquery-ui.min.js"></script>
<script src="<%=request.getContextPath()%>/js/thread.js"></script>
<script src="<%=request.getContextPath()%>/js/delete.js"></script>
<title> <c:out value="${threadInfo.threadName}" /></title>
</head>

<body>
    <div id="returnTop">
        <a href="<%=request.getContextPath()%>/jsp/headline.jsp">掲示板に戻る</a>
    </div><hr>
    <%-- スレッド表示 --%>
    <div id="res">
    <h3><c:out value="${threadInfo.threadName}" /></h3>

    <%-- レス表示 --%>
    <c:forEach var="res" items="${resList}">
        <dl>
        <c:if test="${res.show}">
            <dt>
                ${res.resNum}:
                <c:out value="${res.poster}"/>:
                <fmt:parseDate var="result" value="${res.postDate}" pattern="yyyy-MM-dd HH:mm:ss" />
                <span><fmt:formatDate value="${result}" pattern="yyyy/MM/dd(E) HH:mm:ss" /></span>
                <a href="<%=request.getContextPath()%>/jsp/delete_nonejs.jsp?thread=${threadInfo.threadId}"
                 onClick="openWnd('<%=request.getContextPath()%>/jsp/delete.jsp?thread=${threadInfo.threadId}&num=${res.resNum}'); return false;">削除</a>
                <a target="_blank"
                href="<%=request.getContextPath()%><c:out value="/Draw/${res.imagePath}" />">
                 別ページ
                </a>
            </dt>
            <dd>
                <img src="<%=request.getContextPath()%><c:out value="/Draw/${res.imagePath}" />">
        </c:if>
        <c:if test="${!res.show}">
            <dt>
                ${res.resNum}:
                <c:out value="${res.poster}"/>:
                <fmt:parseDate var="result" value="${res.postDate}" pattern="yyyy-MM-dd HH:mm:ss" />
                <span><fmt:formatDate value="${result}" pattern="yyyy/MM/dd(E) HH:mm:ss" /></span>
            </dt>
            <dd>
                <img src="<%=request.getContextPath()%><c:out value="/Draw/delete.jpg" />">
            </dd>
        </c:if>
        </dl>
    </c:forEach>
    </div>
    <a id="refresh" href="<%=request.getContextPath()%>/jsp/thread.jsp?thread=${threadInfo.threadId}">リロード</a>
    <hr>
    <div id="returnBottom">
        <a href="<%=request.getContextPath()%>/jsp/headline.jsp" onClick=location>掲示板に戻る</a>
    </div>

    <form id="createResForm" autocomplete="off" action="<%=request.getContextPath()%>/PostResServlet" method="post">
    <input id="postRes" type="button" value="書き込む">
    名前:<input type="text" name="poster" size="23" >
    パスワード(半角):<input type="text" name="password" size="10" >
    <input type="hidden" name="id" value="${threadInfo.threadId}">
    <input id="paintData" type="hidden" name="paintData">
    </form>

    <canvas
         id="paint"
         width="<c:out value="${threadInfo.width}"/>"
         height="<c:out value="${threadInfo.height}"/>" >
         このブラウザには対応していません。
    </canvas>

    <div id="paintFunc">
        <button id="resetButton">削除</button>
        <button id="undoButton">やり直し</button>
        <input  id="paintColor" type="text" readonly="readonly" size="8" placeholder="#000000"/>
        <div id="funcSlider">
            <div id="sliderLine"></div>
            <div id="sliderAlpha"></div>
        </div>
    </div>
</body>

<footer>
    <p>Copyright© 2015 PaintShigemi All Rights Reserved</p>
</footer>
</html>